name: CI

on:
  push:
    branches:
      - master

jobs:
  build: 
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14.x]
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install_gitbook_plugins
      run: |
        npm install gitbook-cli -g
        gitbook -v
        gitbook install
    - name: build_gitbook
      run: | 
        gitbook build
    - name: push_to_pages
      run: | 
        cd ./book
        git init
        git config --local user.name "${{ secrets.GIT_NAME }}"
        git config --local user.email "${{ secrets.GIT_EMAIL }}"
        git add *
        git commit -m "Github Actions Auto-Push"
        git push --force "https://${{ secrets.THE_GITHUB_TOKEN }}@{{ secrets.THE_GITHUB_REF }}" master:${{ secrets.RES_FOR_PAGES }}
        git push --force "https://${{ secrets.THE_GITHUB_TOKEN }}@{{ secrets.THE_GITHUB_REF }}" master:${{ secrets.RES_FOR_CODING_PAGES }}
        wget https://raw.githubusercontent.com/Mhy278/MonogatariHelp/master/CNAME
        git init
        git config --local user.name "${{ secrets.GIT_NAME }}"
        git config --local user.email "${{ secrets.GIT_EMAIL }}"
        git add *
        git commit -m "Github Actions Auto-Push"
        git push --force "https://${{ secrets.THE_GITHUB_TOKEN }}@{{ secrets.THE_MonoHelp_REF }}" master:${{ secrets.RES_FOR_PAGES }}

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4

    #   - name: Checkout theme repo
    #     uses: actions/checkout@v4
    #     with:
    #       repository: ${{ env.THEME_REPO }}
    #       ref: ${{ env.THEME_BRANCH }}
    #       path: themes/concise

    #   - name: Checkout deploy repo
    #     uses: actions/checkout@v4
    #     with:
    #       repository: ${{ env.DEPLOY_REPO }}
    #       ref: ${{ env.DEPLOY_BRANCH }}
    #       path: .deploy_git

    #   - name: Use Node.js ${{ matrix.node_version }}
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: ${{ matrix.node_version }}

    #   - name: Configuration environment
    #     env:
    #       HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
    #     run: |
    #       sudo timedatectl set-timezone "Asia/Shanghai"
    #       mkdir -p ~/.ssh/
    #       echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
    #       chmod 600 ~/.ssh/id_rsa
    #       ssh-keyscan github.com >> ~/.ssh/known_hosts
    #       git config --global user.name $GIT_USER
    #       git config --global user.email $GIT_EMAIL
    #       cp _config.theme.yml themes/concise/_config.yml

    #   - name: Install dependencies
    #     run: |
    #       npm install

    #   - name: Deploy hexo
    #     run: |
    #       npm run deploy